return {
  {
    'folke/lazydev.nvim',
    ft = 'lua',
    opts = {
      library = {
        { path = 'luvit-meta/library', words = { 'vim%.uv' } }
      }
    }
  },
  { 'Bilal2453/luvit-meta', lazy = true },
  { 'mason-org/mason.nvim', config = true, lazy = true },
  { 'j-hui/fidget.nvim', config = true }
  -- {
    --
  --   },
  --   config = function()
  --
  --     local servers = {
  --       eslint = {
  --       },
  --       intelephense = {
  --         settings = {
  --           intelephense = {
  --             stubs = {
  --               "apache",
  --               "bcmath",
  --               "bz2",
  --               "calendar",
  --               "com_dotnet",
  --               "Core",
  --               "ctype",
  --               "curl",
  --               "date",
  --               "dba",
  --               "dom",
  --               "enchant",
  --               "exif",
  --               "FFI",
  --               "fileinfo",
  --               "filter",
  --               "fpm",
  --               "ftp",
  --               "gd",
  --               "gettext",
  --               "gmp",
  --               "hash",
  --               "iconv",
  --               "imap",
  --               "intl",
  --               "json",
  --               "ldap",
  --               "libxml",
  --               "mbstring",
  --               "meta",
  --               "mysqli",
  --               "oci8",
  --               "odbc",
  --               "openssl",
  --               "pcntl",
  --               "pcre",
  --               "PDO",
  --               "pdo_ibm",
  --               "pdo_mysql",
  --               "pdo_pgsql",
  --               "pdo_sqlite",
  --               "pgsql",
  --               "Phar",
  --               "posix",
  --               "pspell",
  --               "readline",
  --               "Reflection",
  --               "session",
  --               "shmop",
  --               "SimpleXML",
  --               "snmp",
  --               "soap",
  --               "sockets",
  --               "sodium",
  --               "SPL",
  --               "sqlite3",
  --               "standard",
  --               "superglobals",
  --               "sysvmsg",
  --               "sysvsem",
  --               "sysvshm",
  --               "tidy",
  --               "tokenizer",
  --               "xml",
  --               "xmlreader",
  --               "xmlrpc",
  --               "xmlwriter",
  --               "xsl",
  --               "Zend OPcache",
  --               "zip",
  --               "zlib",
  --               "wordpress"
  --             },
  --             environment = {
  --               includePaths = { "C:/Users/JUANGUI/Downloads/Divi/Divi/" }
  --             },
  --           },
  --         },
  --       },
  --       tailwindcss = {
  --       },
  --       ts_ls = {
  --       },
  --       jsonls = {
  --       },
  --       cssls = {
  --       },
  --       pyright = {
  --       },
  --       svelte = {
  --       },
  --       regal = {
  --       },
  --       lua_ls = {
  --         settings = {
  --           Lua = {
  --             workspace = { checkThirdParty = false },
  --             telemetry = { enable = false },
  --             diagnostics = {
  --               disable = { "missing-fields" }
  --             }
  --           }
  --         }
  --       }
  --     }
  --
  --     require('mason').setup()
  --     local ensure_installed = vim.tbl_keys(servers or {})
  --     vim.list_extend(ensure_installed, {
  --       'stylua',
  --     })
  --
  --     require('mason-tool-installer').setup({ ensure_installed = ensure_installed })
  --
  --     require('mason-lspconfig').setup {
  --       handlers = {
  --         function(server_name)
  --           local server = servers[server_name] or {}
  --           server.capabilities = vim.tbl_deep_extend('force', {}, capabilities, server.capabilities or {})
  --           require('lspconfig')[server_name].setup(server)
  --         end
  --       }
  --     }
  --   end
  -- }
}
